language: python
# whitelist
cache:
  directories:
    - ./pip-cache
branches:
  only:
    - master
    - develop
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy3"
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install --cache-dir pip-cache coveralls
  - pip install --cache-dir pip-cache -r requirements.txt
  - python setup.py develop
# command to run tests
script:
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then py.test --cov-config .coveragerc --cov-report term-missing --cov fireblog; fi
  - if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then py.test; fi
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coveralls; fi
