language: python
# whitelist
branches:
  only:
    - master
    - develop
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "pypy3"
# command to install dependencies
install:
  - python setup.py develop
# command to run tests
script:
  - if [[ $TRAVIS_PYTHON_VERSION != pypy*]]; then py.test --cov-config .coveragerc --cov-report term-missing --cov fireblog; fi
  - if [[ $TRAVIS_PYTHON_VERSION == pypy*]]; then py.test; fi
