"""Add tags

Revision ID: 1251e3d8730
Revises: f2cfc24ece
Create Date: 2015-01-11 15:56:56.419106

"""

# revision identifiers, used by Alembic.
revision = '1251e3d8730'
down_revision = 'f2cfc24ece'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('uuid', sa.Text(), nullable=False),
                    sa.Column('tag', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('uuid')
                    )
    op.create_index(op.f('ix_tags_tag'), 'tags', ['tag'], unique=True)
    op.create_table('post_tags',
                    sa.Column('post_id', sa.Integer(), nullable=True),
                    sa.Column('keyword_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['keyword_id'], ['tags.id'], ),
                    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], )
                    )
    # end Alembic commands ###


def downgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    op.drop_index(op.f('ix_tags_tag'), table_name='tags')
    op.drop_table('tags')
    # end Alembic commands ###
