"""Add usernames

Revision ID: 18cc69056ac
Revises: 222941c2236
Create Date: 2015-03-08 17:18:36.384963

"""

# revision identifiers, used by Alembic.
revision = '18cc69056ac'
down_revision = '222941c2236'

from alembic import op
import sqlalchemy as sa

import datetime
from shortuuid import uuid

from sqlalchemy import (
    Column,
    Index,
    Integer,
    Text,
    DateTime
    )

from sqlalchemy.ext.declarative import declarative_base

from sqlalchemy.orm import (
    scoped_session,
    sessionmaker,
    )


DBSession = scoped_session(sessionmaker())
Base = declarative_base()

class Users(Base):
    __tablename__ = 'users'
    # Note userid will be an email address from mozilla persona
    id = Column(Integer, primary_key = True, nullable = False)
    uuid = Column(Text, unique = True, default = uuid)
    userid = Column(Text, unique = True, index = True, nullable = False)
    username = Column(Text, unique = True)
    group = Column(Text)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.Text()))

    DBSession.configure(bind = op.get_bind())
    for user in DBSession.query(Users):
        if not user.username or post.username == '':
            # We set the username to be the first part of the email address by
            # default.
            user.username = user.userid[:user.userid.find('@')]
    DBSession.commit()
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    ### end Alembic commands ###
