"""Create comments table

Revision ID: 222941c2236
Revises: 1251e3d8730
Create Date: 2015-03-08 16:05:04.142597

"""

# revision identifiers, used by Alembic.
revision = '222941c2236'
down_revision = '1251e3d8730'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('uuid', sa.Text(), nullable=False),
                    sa.Column('post_id', sa.Integer(), nullable=True),
                    sa.Column('author_id', sa.Integer(), nullable=True),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('comment', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('uuid')
                    )
    # end Alembic commands ###


def downgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # end Alembic commands ###
