"""create_settings_table

Revision ID: 2e5a11f02de
Revises: 18cc69056ac
Create Date: 2015-11-10 15:27:57.592462

"""

# revision identifiers, used by Alembic.
revision = '2e5a11f02de'
down_revision = '18cc69056ac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    ### end Alembic commands ###
