"""add post and user table

Revision ID: 320f355c404
Revises: None
Create Date: 2014-10-26 15:44:51.122855

"""

# revision identifiers, used by Alembic.
revision = '320f355c404'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('userid', sa.Text(), nullable=False),
                    sa.Column('group', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_userid'), 'users', ['userid'], unique=True)
    op.create_table('posts',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('markdown', sa.Text(), nullable=True),
                    sa.Column('html', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(
        op.f('ix_posts_created'),
        'posts',
        ['created'],
        unique=False)
    op.create_index(op.f('ix_posts_name'), 'posts', ['name'], unique=True)
    # end Alembic commands ###


def downgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_name'), table_name='posts')
    op.drop_index(op.f('ix_posts_created'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_users_userid'), table_name='users')
    op.drop_table('users')
    # end Alembic commands ###
